### PR TITLE
ENH: improve data copy/gzip process after fetching fastq sequences

### PR DESCRIPTION
**Pull request by misialq**
This PR implements a simple fastq file compressor using Rust to make the process of sequence fetching faster. Similarly to how it was done before, the files are read line-by-line and compressed using the `GzEncoder`. From a quick test, replacing the former implementation with this one offers speedups between 2x (for files of approx. ~50MB) to 5x (for files of approx. ~600MB; have not tried with larger files).

I have fetched a couple of different files using the current implementation and the one proposed here and compared the file contents for 3 different files (2.1MB, 850MB and 3.2GB large) by calculating their MD5 sums. In all three cases the results were the same.

**Testing:**
To test this implementation you need to:
1. Have Rust installed on your machine (https://www.rust-lang.org/tools/install).
2. Install `maturin` in your conda environment: `pip install maturin==0.10.3`.
3. Checkout the PR branch, install fondue, navigate to the `fastq_writer` directory and install the Rust library: `maturin develop --release`.
4. Fetch some sequences.

For speedup comparisons it's best to run `get-sequences` with `n_jobs = 1` to exclude influence of parallelization.

To be merged after #140.

### CODE REVIEW

**Review by adamovanja — CHANGES_REQUESTED** [review]
Thanks for this addition @misialq 🚀 . The method runs smoothly and code looks good as far as my Rust-judgment goes. 
One change request though: Could you add the new installation instructions to the ReadMe and tutorial?

As for runtime: 
I tested the `get-sequences` (`--p-n-jobs=1`) with three different accession IDs comparing the former implementation (MAIN) to the rusty enhanced version (RUST) with regards to total runtime and size of output artifact:

| accession ID | MAIN size | RUST size | MAIN time | RUST time |
| ------- |------- |------- |------- |------- |
| ERR184806 | 11.5 MB| 11.8 MB | 35 s | 22 s |
| SRP132205 | 70.3 MB| 74.5 MB | 16:04 min | 16:10 min |
| PRJEB16321 | 65.2 MB| 67.9 MB | 12:50 min | 12:39 min |

It seems the Rust compression is slightly larger and the overall `get-seqences` runtime for smaller files (<100MB) is similar - I assume this is due to network variations. Is this in accordance to your experience?

(Also, outputs were the same for randomly picked run ID hashes of above mentioned accessions 🥳 )

**Comment by misialq** [comment]
Heyo @adamovanja, thanks for testing! I am realizing only now that making these comparisons on such small files is very difficult actually... Sorry! I should have mentioned in the PR description 🤦  The reason for this is that for those cases q2-fondue spends the majority of time on the download of the raw data and the actual processing happens in parallel (so it actually is mostly finished by the time all the data is downloaded). The differences start becoming visible when a single run is >50MB and you have a couple of those to process. If you have the logs you could compare the times between the "Download finished." and "Processing finished." steps to get a better idea... 

So, to answer you question, yes, that is consistent with what I have seen and the times you reported here should, if anything, be considered equal (as you said, due to network-based variation). Also the compression difference is something I have seen. There are some other algorithms available in that package so we could explore those as a folow-up to this PR, if needed. 

As to the instructions: good catch! Yes, I'll add those. Maybe it's also time for us to change the instructions to start using conda (follow-up PR)? It should all be available there now and would make the installation much easier.

**Comment by adamovanja** [comment]
agree on both follow-up PR suggestions 👍🏼

**Review by adamovanja — APPROVED** [review]
thanks for updating the installation instructions. This is ready to be merged from my side 🌟

**Pull request merged**
